function [net] = trainNet(imgDataTrain, imgDataTest, layers, learningRate, maxEpochs, miniBatchSize)
    options = trainingOptions('sgdm', ...
        'InitialLearnRate', learningRate, ...
        'MiniBatchSize', miniBatchSize, ...
        'MaxEpochs', maxEpochs, ...
        'Shuffle', 'every-epoch', ...
        'ValidationData', imgDataTest, ...
        'ValidationFrequency', 300, ...
        'Verbose', false, ...
        'Plots', 'training-progress');

    net = trainNetwork(imgDataTrain, layers, options);
end